server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # Route 1: Auth requests → user-service
        - id: user-auth-route
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        # Route 2: Quantity measurement requests → measurement-service
        - id: measurement-route
          uri: lb://measurement-service
          predicates:
            - Path=/api/v1/quantities/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
